# Generated by Django 4.0 on 2022-02-15 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'verbose_name': 'task list', 'verbose_name_plural': 'task'},
        ),
    ]
